import { AppLanguage } from '../types';

const translations = {
  fr: {
    loginError: "Identifiants incorrects.",
    loginErrorGeneric: "Une erreur est survenue lors de la connexion.",
    loginExpertiseCert: "La certitude de l'expertise.",
    loginSpace: "Espace",
    loginIdPlaceholder: "Identifiant",
    loginPasswordPlaceholder: "Mot de passe",
    loginButton: "Se connecter",
    loginSecuredAccess: "Accès Sécurisé",
    logoutConfirmTitle: "Déconnexion ?",
    logoutConfirmText: "Êtes-vous sûr de vouloir quitter votre session de travail ?",
    cancel: "Annuler",
    confirm: "Confirmer",
    updatePhoto: "Modifier la photo",
    logout: "Se déconnecter",
    roleAdmin: "ADMINISTRATEUR",
    roleUser: "UTILISATEUR",
    tabDashboard: "Tableau de Bord",
    tabScan: "Scan",
    tabHistory: "Historique",
    tabChat: "IA Expert",
    tabConfig: "Configuration",
    dashboardTitle: "Pilotage",
    dashboardSubtitle: "Supervision du parc automobile.",
    dashboardVN: "Neuf",
    dashboardVO: "Occasion",
    dashboardExpertiseFeed: "Flux d'Expertises",
    dashboardEmptyRegister: "Registre vide",
    dashboardFleetByBrand: "Parc par Marque",
    dashboardAvgDurations: "Performance Système",
    dashboardScanTime: "Temps moyen Scan IA",
    dashboardDeepAnalysisTime: "Temps moyen Expertise VIN",
    dashboardAwaitingData: "Attente données",
    dashboardGlobalStatus: "Statut Global",
    dashboardRecentActivity: "Activité Récente",
    dashboardExpertisesDone: "expertises réalisées.",
    dashboardNotAvailable: "N/A",
    dashboardTokenBalance: "Solde IA Restant",
    dashboardDailyQuota: "Quota Journalier",
    dashboardRemainingExpertises: "Expertises restantes",
    dashboardPlanFree: "PLAN GRATUIT",
    scannerLocation: "Emplacement",
    scannerSelectLocation: "Veuillez sélectionner l'emplacement avant de commencer le scan.",
    scannerCurrentLocation: "Emplacement actuel",
    scannerConfirmAndLaunch: "Confirmer & Lancer",
    scannerChange: "Changer",
    scannerScanVehicle: "Scanner le Véhicule",
    scannerPositionPrompt: "Positionnez le VIN ou la Carte Grise.",
    scannerUseCamera: "Utiliser la Caméra",
    scannerImportGallery: "Importer de la Galerie",
    scannerIAAnalysisFailed: "Analyse IA échouée. Veuillez réessayer avec une image plus nette.",
    scannerQuotaError: "Quota API Google atteint.",
    scannerWaitPrompt: "Veuillez patienter quelques instants avant de réessayer.",
    scannerDataCorrection: "Correction des Données",
    scannerBrand: "Marque",
    scannerModel: "Modèle",
    scannerVIN: "VIN (Numéro de châssis)",
    scannerLicensePlate: "Immatriculation",
    scannerRegistrationYear: "1ère Mise en circ.",
    scannerFabYear: "Année de fabrication",
    scannerType: "Type",
    scannerRemarks: "Remarques Inventaire",
    scannerRemarksPlaceholder: "État carrosserie, accessoires, pneus, intérieur...",
    scannerValidateAndSave: "Valider & Enregistrer",
    scannerDuplicateWarning: "Ce VIN a déjà été scanné par {user} il y a moins de {hours}h.",
    scannerVehicleAdded: "Véhicule {brand} {model} ajouté.",
    scannerColor: "Couleur",
    scannerColorPlaceholder: "Ex: Noir Métallisé",
    scannerMotorization: "Motorisation",
    historyTitle: "Historique",
    historySubtitle: "Registre complet des expertises.",
    historyResetRegister: "Réinitialiser",
    historyExport: "Exporter CSV",
    historySearchPlaceholder: "Rechercher VIN, Marque, Plaque...",
    historyNoVehicleFound: "Aucun véhicule trouvé.",
    historyFab: "Fab",
    historyImmat: "Immat",
    historyResetConfirmTitle: "Vider l'historique ?",
    historyResetConfirmText: "Cette action supprimera définitivement les {count} expertises enregistrées.",
    historyResetConfirmButton: "Oui, tout effacer",
    backToInventory: "Retour Inventaire",
    certifiedScan: "Scan Certifié",
    datasheet: "Fiche Technique",
    energy: "Énergie",
    vinAnalysis: "Expertise Profonde",
    vinAnalysisTitle: "Rapport d'Expertise IA",
    vinAnalysisLoading: "Analyse technique en cours...",
    vinAnalysisError: "Impossible de générer le rapport.",
    vinAnalysisQuotaError: "Limite de quota atteinte pour l'analyse profonde.",
    chatWelcome: "Bonjour, je suis Khabir, votre assistant IA expert {appName}. Comment puis-je vous aider aujourd'hui ?",
    chatPlaceholder: "Posez votre question technique...",
    chatDisclaimer: "IA expérimentale - Vérifiez les informations critiques.",
    configTitle: "Configuration",
    configSubtitle: "Gestion des accès et paramètres.",
    configCompanyParams: "Paramètres Société",
    configCompany: "Nom de l'entreprise",
    configCompanyNamePlaceholder: "Ex: Auto Expert Maroc",
    configDuplicateAlertDelay: "Délai alerte doublon (heures)",
    configDuplicateAlertHelp: "Empêche de scanner deux fois le même véhicule par erreur.",
    configLanguage: "Langue de l'interface",
    configCompanyParamsDenied: "Accès paramètres société réservé.",
    configLocationsManagement: "Gestion des Emplacements",
    configNewLocationPlaceholder: "Nouvel emplacement...",
    configLocationsDenied: "Accès emplacements réservé.",
    configTeamAndAccess: "Équipe & Access",
    configIdentity: "Identité",
    configFullNamePlaceholder: "Nom complet",
    configUsernamePlaceholder: "Identifiant",
    configPasswordPlaceholder: "Mot de passe",
    configRoleAndPermissions: "Rôle & Permissions",
    configRoleUser: "Agent",
    configRoleAdmin: "Administrateur",
    configMainModules: "Modules Principaux",
    configPermDashboard: "Tableau de Bord",
    configPermScanner: "Scanner",
    configPermHistory: "Historique",
    configPermChat: "IA Chat",
    configPermAccessConfig: "Accès Config",
    configPermCompany: "Config Société",
    configPermLocations: "Config Lieux",
    configPermUsers: "Config Users",
    configConfigDetails: "Détails Configuration",
    configAccessAllowed: "Accès Autorisé",
    configAccessBlocked: "Accès Bloqué",
    configCreateAccount: "Créer le Compte",
    configTeamDenied: "Accès gestion équipe réservé.",
    french: "Français",
    arabic: "العربية",
    amazigh: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
    estimateValue: "Estimer la Valeur",
    valueEstimated: "Valeur Estimée",
    marketValue: "Valeur Marché (MAD)",
    estimationLoading: "Calcul de la valeur marchande...",
    estimationJustification: "Justification de l'Estimation",
    historyAdvancedFilters: "Filtres avancés",
    historyFilterByUser: "Filtrer par utilisateur",
    historyFilterByLocation: "Filtrer par emplacement",
    historyFilterByDate: "Filtrer par date",
    historyAllUsers: "Tous les utilisateurs",
    historyAllLocations: "Tous les emplacements",
    historyFrom: "Du",
    historyTo: "Au",
    historyResetFilters: "Réinitialiser les filtres",
  },
  ar: {
    loginError: "بيانات الاعتماد غير صحيحة.",
    loginErrorGeneric: "حدث خطأ أثناء الاتصال.",
    loginExpertiseCert: "يقين الخبرة.",
    loginSpace: "فضاء",
    loginIdPlaceholder: "المعرف",
    loginPasswordPlaceholder: "كلمة المرور",
    loginButton: "تسجيل الدخول",
    loginSecuredAccess: "ولوج مؤمن",
    logoutConfirmTitle: "تسجيل الخروج؟",
    logoutConfirmText: "هل أنت متأكد أنك تريد مغادرة جلسة العمل الخاصة بك؟",
    cancel: "إلغاء",
    confirm: "تأكيد",
    updatePhoto: "تعديل الصورة",
    logout: "تسجيل الخروج",
    roleAdmin: "مدير",
    roleUser: "مستخدم",
    tabDashboard: "لوحة القيادة",
    tabScan: "مسح",
    tabHistory: "السجل",
    tabChat: "خبير الذكاء الاصطناعي",
    tabConfig: "الإعدادات",
    dashboardTitle: "القيادة",
    dashboardSubtitle: "الإشراف على حظيرة السيارات.",
    dashboardVN: "جديد",
    dashboardVO: "مستعمل",
    dashboardExpertiseFeed: "تدفق الخبرات",
    dashboardEmptyRegister: "سجل فارغ",
    dashboardFleetByBrand: "الحظيرة حسب العلامة",
    dashboardAvgDurations: "أداء النظام",
    dashboardScanTime: "متوسط وقت المسح",
    dashboardDeepAnalysisTime: "متوسط وقت خبرة VIN",
    dashboardAwaitingData: "في انتظار البيانات",
    dashboardGlobalStatus: "الحالة العامة",
    dashboardRecentActivity: "النشاط الأخير",
    dashboardExpertisesDone: "خبرات منجزة.",
    dashboardNotAvailable: "غير متوفر",
    dashboardTokenBalance: "رصيد الذكاء الاصطناعي",
    dashboardDailyQuota: "الحصة اليومية",
    dashboardRemainingExpertises: "الخبرات المتبقية",
    dashboardPlanFree: "خطة مجانية",
    scannerLocation: "الموقع",
    scannerSelectLocation: "يرجى اختيار الموقع قبل البدء في المسح.",
    scannerCurrentLocation: "الموقع الحالي",
    scannerConfirmAndLaunch: "تأكيد وإطلاق",
    scannerChange: "تغيير",
    scannerScanVehicle: "مسح السيارة",
    scannerPositionPrompt: "ضع رقم الهيكل أو البطاقة الرمادية.",
    scannerUseCamera: "استخدام الكاميرا",
    scannerImportGallery: "استيراد من المعرض",
    scannerIAAnalysisFailed: "فشل تحليل الذكاء الاصطناعي. يرجى المحاولة بصورة أوضح.",
    scannerQuotaError: "تم الوصول إلى حصة Google API.",
    scannerWaitPrompt: "يرجى الانتظار لحظات قبل المحاولة مرة أخرى.",
    scannerDataCorrection: "تصحيح البيانات",
    scannerBrand: "العلامة",
    scannerModel: "الموديل",
    scannerVIN: "رقم الهيكل (VIN)",
    scannerLicensePlate: "الترقيم",
    scannerRegistrationYear: "تاريخ أول استخدام",
    scannerFabYear: "سنة الصنع",
    scannerType: "النوع",
    scannerRemarks: "ملاحظات الجرد",
    scannerRemarksPlaceholder: "حالة الهيكل، الملحقات، الإطارات، التصميم الداخلي...",
    scannerValidateAndSave: "تأكيد وحفظ",
    scannerDuplicateWarning: "تم مسح هذا الرقم بالفعل بواسطة {user} منذ أقل من {hours} ساعات.",
    scannerVehicleAdded: "تمت إضافة السيارة {brand} {model}.",
    scannerColor: "اللون",
    scannerColorPlaceholder: "مثال: أسود ميتاليك",
    scannerMotorization: "المحرك",
    historyTitle: "السجل",
    historySubtitle: "سجل كامل للخبرات.",
    historyResetRegister: "إعادة ضبط",
    historyExport: "تصدير CSV",
    historySearchPlaceholder: "بحث عن VIN، علامة، لوحة...",
    historyNoVehicleFound: "لم يتم العثور على أي سيارة.",
    historyFab: "صنع",
    historyImmat: "ترقيم",
    historyResetConfirmTitle: "مسح السجل؟",
    historyResetConfirmText: "سيؤدي هذا الإجراء إلى حذف {count} خبرات مسجلة نهائيًا.",
    historyResetConfirmButton: "نعم، امسح الكل",
    backToInventory: "العودة للجرد",
    certifiedScan: "مسح معتمد",
    datasheet: "البطاقة التقنية",
    energy: "الطاقة",
    vinAnalysis: "خبرة عميقة",
    vinAnalysisTitle: "تقرير خبرة الذكاء الاصطناعي",
    vinAnalysisLoading: "تحليل تقني جارٍ...",
    vinAnalysisError: "تعذر إنشاء التقرير.",
    vinAnalysisQuotaError: "تم الوصول إلى حد الحصة للتحليل العميق.",
    chatWelcome: "مرحباً، أنا خبير، مساعدك الذكي في {appName}. كيف يمكنني مساعدتك اليوم؟",
    chatPlaceholder: "اطرح سؤالك التقني...",
    chatDisclaimer: "ذكاء اصطناعي تجريبي - تحقق من المعلومات الهامة.",
    configTitle: "الإعدادات",
    configSubtitle: "إدارة الولوج والمعايير.",
    configCompanyParams: "إعدادات الشركة",
    configCompany: "اسم الشركة",
    configCompanyNamePlaceholder: "مثال: أوتو إكسبرت المغرب",
    configDuplicateAlertDelay: "مهلة تنبيه التكرار (ساعات)",
    configDuplicateAlertHelp: "يمنع مسح نفس السيارة مرتين عن طريق الخطأ.",
    configLanguage: "لغة الواجهة",
    configCompanyParamsDenied: "الولوج إلى إعدادات الشركة محظور.",
    configLocationsManagement: "إدارة المواقع",
    configNewLocationPlaceholder: "موقع جديد...",
    configLocationsDenied: "الولوج إلى المواقع محظور.",
    configTeamAndAccess: "الفريق والولوج",
    configIdentity: "الهوية",
    configFullNamePlaceholder: "الاسم الكامل",
    configUsernamePlaceholder: "المعرف",
    configPasswordPlaceholder: "كلمة المرور",
    configRoleAndPermissions: "الدور والصلاحيات",
    configRoleUser: "وكيل",
    configRoleAdmin: "مدير",
    configMainModules: "الوحدات الرئيسية",
    configPermDashboard: "لوحة القيادة",
    configPermScanner: "ماسح",
    configPermHistory: "السجل",
    configPermChat: "محادثة الذكاء الاصطناعي",
    configPermAccessConfig: "ولوج الإعدادات",
    configPermCompany: "إعدادات الشركة",
    configPermLocations: "إعدادات المواقع",
    configPermUsers: "إعدادات المستخدمين",
    configConfigDetails: "تفاصيل الإعدادات",
    configAccessAllowed: "الولوج مسموح",
    configAccessBlocked: "الولوج محظور",
    configCreateAccount: "إنشاء الحساب",
    configTeamDenied: "الولوج لإدارة الفريق محظور.",
    french: "الفرنسية",
    arabic: "العربية",
    amazigh: "الأمازيغية",
    estimateValue: "تقدير القيمة",
    valueEstimated: "القيمة المقدرة",
    marketValue: "قيمة السوق (درهم)",
    estimationLoading: "جاري حساب قيمة السوق...",
    estimationJustification: "مبررات التقدير",
    historyAdvancedFilters: "فلاتر متقدمة",
    historyFilterByUser: "تصفية حسب المستخدم",
    historyFilterByLocation: "تصفية حسب الموقع",
    historyFilterByDate: "تصفية حسب التاريخ",
    historyAllUsers: "كل المستخدمين",
    historyAllLocations: "كل المواقع",
    historyFrom: "من",
    historyTo: "إلى",
    historyResetFilters: "إعادة ضبط الفلاتر",
  }
};

export type TranslationKey = keyof typeof translations.fr;

export const t = (key: TranslationKey, lang: AppLanguage, options?: Record<string, string | number>) => {
  let translation = translations[lang][key] || translations.fr[key] || key;
  if (options) {
    Object.keys(options).forEach(optionKey => {
      translation = translation.replace(`{${optionKey}}`, String(options[optionKey]));
    });
  }
  return translation;
};
